
[config] # Include this if it's not already in your file

# caffyne shell Color Generation
[templates.caffyne]
input_path = '~/.config/caffyne-shell/matugen/caffyne-shell-colors.css'
output_path = '~/.config/caffyne-shell/style/colors.css'

[config]
